### ISSUE TITLE
Spinal cord release r20220623 missing T1, MTsat and MTR data.

### ISSUE THREAD

**Issue by mathieuboudreau** [courtois-neuromod/anat-processing#30]
These are the only files obtained when downloaded:
<img width="298" alt="Screen Shot 2022-06-23 at 12 58 01 PM" src="https://user-images.githubusercontent.com/1421029/175343002-91364156-ee0c-49ba-a188-a9a04f703f8f.png">

Whereas release r20210610 had all these extra CSV files:
<img width="298" alt="Screen Shot 2022-06-23 at 12 59 04 PM" src="https://user-images.githubusercontent.com/1421029/175343258-8f09e8bb-dad3-4b86-b5ba-3c291a2a752b.png">

**Comment by jcohenadad** [comment]
thank you @mathieuboudreau -- i didn't have the time to properly review the outputs but, yes, something clearly went wrong... i'll fix it and re-release

**Comment by jcohenadad** [comment]
One first clue:
~~~
sct_deepseg_sc -i sub-01_ses-001_acq-T1w_bp-cspine_MTS.nii.gz -c t1 -qc /mnt/nvme/p101317/neuromod/results_20220622_180921/qc -qc-subject sub-01_ses-001
--

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nvme/p101317/neuromod/results_20220622_180921/data_processed/sub-01/ses-001/anat/sub-01_ses-001_acq-T1w_bp-cspine_MTS.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 214, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 190, in main
    check_dim(fname_image, dim_lst=[2, 3])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/image.py", line 1439, in check_dim
    dim = Image(fname).hdr['dim'][:4]
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/image.py", line 285, in __init__
    self.loadFromPath(param, verbose)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/image.py", line 406, in loadFromPath
    im_file = nib.load(self.absolutepath, mmap=(not sys.platform.startswith('win32')))
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.7/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/mnt/nvme/p101317/neuromod/results_20220622_180921/data_processed/sub-01/ses-001/anat/sub-01_ses-001_acq-T1w_bp-cspine_MTS.nii.gz'
~~~

**Comment by jcohenadad** [comment]
ah! it looks like the files were renamed (probably to fit BIDS' new convention):
~~~
p101317@joplin:~/data_nvme_p101317/neuromod/anat/sub-01/ses-001/anat$ ll *MTS.*
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_bp-cspine_flip-1_mt-off_MTS.nii.gz -> ../../../.git/annex/objects/0z/11/MD5E-s1802510--ba5d949cf27d6579b2da8b15a2a9f3d6.nii.gz/MD5E-s1802510--ba5d949cf27d6579b2da8b15a2a9f3d6.nii.gz
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_bp-cspine_flip-1_mt-on_MTS.nii.gz -> ../../../.git/annex/objects/ZZ/fG/MD5E-s1887531--1b98267a8741b0ecc5e1a2e8f83ca9ab.nii.gz/MD5E-s1887531--1b98267a8741b0ecc5e1a2e8f83ca9ab.nii.gz
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_bp-cspine_flip-2_mt-off_MTS.nii.gz -> ../../../.git/annex/objects/6Q/xg/MD5E-s1870184--31d491f6788c523ea6f4e660dfa48ca3.nii.gz/MD5E-s1870184--31d491f6788c523ea6f4e660dfa48ca3.nii.gz
-rw------- 1 p101317 domain users  9336 Jun 22 14:24 sub-01_ses-001_flip-1_mt-off_bp-cspine_MTS.json
-rw------- 1 p101317 domain users 26377 Jun 22 14:24 sub-01_ses-001_flip-1_mt-off_MTS.json
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_flip-1_mt-off_MTS.nii.gz -> ../../../.git/annex/objects/Jm/Mk/MD5E-s2259597--dfc1f9559195016a872595c00f6c5199.nii.gz/MD5E-s2259597--dfc1f9559195016a872595c00f6c5199.nii.gz
-rw------- 1 p101317 domain users  9427 Jun 22 14:24 sub-01_ses-001_flip-1_mt-on_bp-cspine_MTS.json
-rw------- 1 p101317 domain users 26438 Jun 22 14:24 sub-01_ses-001_flip-1_mt-on_MTS.json
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_flip-1_mt-on_MTS.nii.gz -> ../../../.git/annex/objects/X7/MW/MD5E-s2167492--fc137b568f88c8378c317e4a506206aa.nii.gz/MD5E-s2167492--fc137b568f88c8378c317e4a506206aa.nii.gz
-rw------- 1 p101317 domain users  9216 Jun 22 14:24 sub-01_ses-001_flip-2_mt-off_bp-cspine_MTS.json
-rw------- 1 p101317 domain users 26395 Jun 22 14:24 sub-01_ses-001_flip-2_mt-off_MTS.json
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_flip-2_mt-off_MTS.nii.gz -> ../../../.git/annex/objects/5X/vX/MD5E-s2314636--54a82063aa12a094c33c9f7939719dd9.nii.gz/MD5E-s2314636--54a82063aa12a094c33c9f7939719dd9.nii.gz
-rw------- 1 p101317 domain users 26407 Jun 22 14:24 sub-01_ses-001_rec-dis2d_flip-1_mt-off_MTS.json
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_rec-dis2d_flip-1_mt-off_MTS.nii.gz -> ../../../.git/annex/objects/Vg/MM/MD5E-s2228202--d5b1e455f519aa4d1bbd8028b6db82df.nii.gz/MD5E-s2228202--d5b1e455f519aa4d1bbd8028b6db82df.nii.gz
-rw------- 1 p101317 domain users 26467 Jun 22 14:24 sub-01_ses-001_rec-dis2d_flip-1_mt-on_MTS.json
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_rec-dis2d_flip-1_mt-on_MTS.nii.gz -> ../../../.git/annex/objects/Wm/3Z/MD5E-s2136235--1737f02bbbb9445796f00b9e97300915.nii.gz/MD5E-s2136235--1737f02bbbb9445796f00b9e97300915.nii.gz
-rw------- 1 p101317 domain users 26425 Jun 22 14:24 sub-01_ses-001_rec-dis2d_flip-2_mt-off_MTS.json
lrwxrwxrwx 1 p101317 domain users   143 Jun 22 14:24 sub-01_ses-001_rec-dis2d_flip-2_mt-off_MTS.nii.gz -> ../../../.git/annex/objects/Jw/W0/MD5E-s2283535--159f770f567419f0213ad75917a1ec99.nii.gz/MD5E-s2283535--159f770f567419f0213ad75917a1ec99.nii.gz
~~~

**Comment by jcohenadad** [comment]
However, I am now running into another issue: https://github.com/courtois-neuromod/cneuromod_docs/issues/69

**Comment by mathieuboudreau** [comment]
Latest spinal cord published release also missing T2s output.
